@ShipsAPI_HostAddress = http://localhost:5127

# Nová hra
POST {{ShipsAPI_HostAddress}}/api/battleship/games
Content-Type: application/json

{
  "player1": "Radek",
  "player2": "Vojta",
  "boardSize": 10
}

###


# Výstøel Player 1
POST {{ShipsAPI_HostAddress}}/api/battleship/fire
Content-Type: application/json

{
  "playerName": "Radek",
  "x": 4,
  "y": 9
}
###

# Výstøel Player 2
POST {{ShipsAPI_HostAddress}}/api/battleship/fire
Content-Type: application/json

{
  "playerName": "Vojta",
  "x": 5,
  "y": 3
}

###


# Je hra u konce?
GET {{ShipsAPI_HostAddress}}/api/battleship/status

###

# Výherce?
GET {{ShipsAPI_HostAddress}}/api/battleship/winner

###

# Výherce?
GET {{ShipsAPI_HostAddress}}/api/battleship/turn

###

